project:
  title: "Lab 07"
  type: website

website:
  title: "Data alchemy"
  sidebar:
    style: "docked"
    contents:
      - index.qmd
      - section: "Process"
        contents: process/*
format:
  html:
    theme: cosmo
